# .goprojectstarter.yaml
# 定义可用的 LLM 模型提供商和名称

llm:
  # 当用户不选择时，默认使用的模型
  default: deepseek:deepseek-chat

  # 定义所有可用的提供商
  providers:
    openai:
      models:
        - "gpt-4o"
        - "gpt-4o-mini"
        - "gpt-3.5-turbo"
    gemini:
      models:
        - "gemini-1.5-pro-latest"
        - "gemini-1.5-flash-latest"
    deepseek:
      models:
        - "deepseek-chat"
    volc:
      models:
